# Generated by Django 2.0.5 on 2018-11-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AideRecu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Association')),
            ],
            options={
                'verbose_name': 'Aide reçu',
                'verbose_name_plural': 'Aides reçus',
            },
        ),
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_urgent', models.BooleanField(default=False)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('montant', models.IntegerField(blank=True, default=0, null=True)),
                ('date_planification', models.DateField(blank=True, null=True)),
                ('date_remise_don', models.DateField(blank=True, null=True)),
                ('est_satisfait', models.BooleanField(default=False)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Association')),
            ],
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.CentreType')),
            ],
        ),
        migrations.CreateModel(
            name='Donneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=False)),
                ('anonyme', models.BooleanField(default=True)),
                ('association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Association')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.DonneurType')),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('nombre_enfant', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('archivé', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Necessiteux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField(null=True)),
                ('sexe', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('pointure', models.IntegerField(null=True)),
                ('taille', models.CharField(max_length=100, null=True)),
                ('est_orphelin', models.BooleanField()),
                ('degré_nécessite', models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('represent_famille', models.BooleanField(default=False)),
                ('archivé', models.BooleanField(default=False)),
                ('appartient_famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charity.Famille')),
                ('association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='staff.Association')),
                ('niveau_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.NiveauScolaire')),
                ('situation_familiale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.SituationFamiliale')),
                ('situation_professionelle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.SituationProfessionelle')),
            ],
            options={
                'verbose_name': 'Nécessiteux',
                'verbose_name_plural': 'Nécessiteux',
            },
        ),
        migrations.AddField(
            model_name='besoin',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.Centre'),
        ),
        migrations.AddField(
            model_name='besoin',
            name='necessiteux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.Necessiteux'),
        ),
        migrations.AddField(
            model_name='besoin',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.DonType'),
        ),
        migrations.AddField(
            model_name='aiderecu',
            name='donneur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charity.Donneur'),
        ),
        migrations.AddField(
            model_name='aiderecu',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.DonType'),
        ),
    ]
