# Generated by Django 2.0.5 on 2018-10-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='archivé',
            field=models.BooleanField(default=False),
        ),
    ]
