# Generated by Django 2.0.9 on 2019-02-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20190209_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessiteux',
            name='est_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='tél'),
        ),
    ]
