# Generated by Django 2.0.5 on 2018-06-29 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20180501_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoin',
            name='centre',
            field=models.ManyToManyField(blank=True, to='charity.Centre'),
        ),
        migrations.AlterField(
            model_name='association',
            name='responsable',
            field=models.ForeignKey(limit_choices_to={'profile': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='necessiteux',
            field=models.ManyToManyField(blank=True, to='charity.Necessiteux'),
        ),
    ]
