# Generated by Django 2.0.5 on 2018-07-09 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_auto_20180629_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besoin',
            name='centre',
        ),
        migrations.AddField(
            model_name='besoin',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.Centre'),
        ),
        migrations.RemoveField(
            model_name='besoin',
            name='necessiteux',
        ),
        migrations.AddField(
            model_name='besoin',
            name='necessiteux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.Necessiteux'),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='degre_necessite',
            field=models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
