# Generated by Django 2.0.9 on 2019-02-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_auto_20190209_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessiteux',
            name='appartient_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charity.Centre'),
        ),
    ]
