# Generated by Django 2.0.5 on 2018-07-09 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_auto_20180709_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='associations',
        ),
    ]
