# Generated by Django 2.0.5 on 2018-07-09 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_remove_centre_associations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='necessiteux',
            old_name='degre_necessite',
            new_name='degree_necessite',
        ),
    ]
