# Generated by Django 2.0.9 on 2019-02-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_auto_20190209_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besoin',
            name='necessiteux',
        ),
        migrations.AddField(
            model_name='besoin',
            name='necessiteux',
            field=models.ManyToManyField(blank=True, null=True, to='charity.Necessiteux'),
        ),
    ]
