# Generated by Django 2.0.9 on 2019-03-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_auto_20190216_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='necessiteux',
            name='est_permanent',
        ),
        migrations.AddField(
            model_name='necessiteux',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Permanent'), (1, 'Temporaire'), (2, 'Voyageur en détresse')], default=0),
        ),
    ]
