# Generated by Django 2.0.5 on 2018-07-09 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_auto_20180709_0231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiderecu',
            options={'verbose_name': 'Aide reçu', 'verbose_name_plural': 'Aides reçus'},
        ),
        migrations.AlterModelOptions(
            name='necessiteux',
            options={'verbose_name': 'Nécessiteux', 'verbose_name_plural': 'Nécessiteux'},
        ),
        migrations.RenameField(
            model_name='besoin',
            old_name='besoin_satisfait',
            new_name='est_satisfait',
        ),
        migrations.RenameField(
            model_name='donneur',
            old_name='est_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='necessiteux',
            old_name='archive',
            new_name='archivé',
        ),
        migrations.RenameField(
            model_name='necessiteux',
            old_name='degree_necessite',
            new_name='degré_nécessite',
        ),
        migrations.RemoveField(
            model_name='aiderecu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='donneur',
            name='association',
        ),
        migrations.AddField(
            model_name='aiderecu',
            name='notes',
            field=models.TextField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='aiderecu',
            name='donneur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charity.Donneur'),
        ),
        migrations.AlterField(
            model_name='aiderecu',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.DonType'),
        ),
        migrations.AlterField(
            model_name='association',
            name='facebook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='association',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='youtube',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='date_planification',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='montant',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.DonneurType'),
        ),
        migrations.AlterField(
            model_name='famille',
            name='nombre_enfant',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='appartient_famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charity.Famille'),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='niveau_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.NiveauScolaire'),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='pointure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='situation_familiale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.SituationFamiliale'),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='situation_professionelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.SituationProfessionelle'),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='taille',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
