# Generated by Django 2.0.5 on 2018-07-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_auto_20180709_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiderecu',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
