# Generated by Django 2.0.9 on 2019-03-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_besoin_expire_le'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessiteux',
            name='jeune_fille',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de jeune fille'),
        ),
    ]
