# Generated by Django 2.0.5 on 2018-07-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_auto_20180709_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='association',
            name='responsable',
        ),
    ]
