# Generated by Django 2.0.5 on 2018-07-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_auto_20180709_1123'),
        ('staff', '0002_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneur',
            name='association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.Association'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aiderecu',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Association'),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Association'),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='staff.Association'),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='date_de_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='pointure',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='situation_familiale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.SituationFamiliale'),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='situation_professionelle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.SituationProfessionelle'),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='taille',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Association',
        ),
    ]
