# Generated by Django 2.0.9 on 2019-04-02 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_necessiteux_jeune_fille'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoin',
            name='délivré_par',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='necessiteux',
            name='nin',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Champ invalide', regex='\\d{9}$')], verbose_name='Numéro pièce d’identité'),
        ),
        migrations.AddField(
            model_name='necessiteux',
            name='part_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='De la part de'),
        ),
    ]
