# Generated by Django 2.0.9 on 2019-10-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0010_auto_20190402_1823'),
        ('charity', '0002_auto_20191028_0621'),
    ]

    operations = [
    ]
