# Generated by Django 2.0.9 on 2019-10-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0011_merge_20191028_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='necessiteux',
            name='appartient_centre',
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='tél'),
        ),
    ]
