# Generated by Django 2.0.9 on 2019-10-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0012_auto_20191028_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessiteux',
            name='nin',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Numéro pièce d’identité'),
        ),
        migrations.AlterField(
            model_name='necessiteux',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone 1'),
        ),
    ]
