# Generated by Django 2.0.9 on 2019-10-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0014_auto_20191028_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessiteux',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='adresse postale'),
        ),
    ]
