# Generated by Django 2.0.5 on 2018-07-09 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180709_0133'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500, unique=True)),
                ('surnom', models.CharField(blank=True, max_length=100, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('telephone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube', models.CharField(blank=True, max_length=500, null=True)),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Commune')),
                ('responsable', models.ForeignKey(blank=True, limit_choices_to={'profile': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
