# Generated by Django 2.0.9 on 2019-02-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20181109_0341'),
        ('staff', '0002_auto_20181108_1944'),
    ]

    operations = [
    ]
