# Generated by Django 2.0.5 on 2018-07-09 11:45

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0002_association'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='membre',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='membre',
            old_name='profile',
            new_name='profil',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='membre',
            name='nom',
            field=models.CharField(default='anonym', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membre',
            name='prénom',
            field=models.CharField(default='anonym', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membre',
            name='tel',
            field=models.CharField(default='999', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membre',
            name='user',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='association',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Membre'),
        ),
        migrations.AlterField(
            model_name='login',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Membre'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='membre',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='membre',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
