# Generated by Django 2.0.9 on 2019-10-28 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20181108_1944'),
        ('staff', '0002_auto_20181109_0341'),
    ]

    operations = [
    ]
