# Generated by Django 2.0.9 on 2019-10-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_merge_20191028_0604'),
        ('staff', '0003_merge_20190210_0945'),
    ]

    operations = [
    ]
