# Generated by Django 2.0.5 on 2018-10-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dontype',
            name='label',
            field=models.CharField(choices=[('Argents', 'Argents'), ('Services', 'Services'), ('Vêtements', 'Vêtements'), ('Jouets', 'Jouets'), ('Nourritures', 'Nourritures'), ('Véhicules', 'Véhicules'), ('Premiers Secours', 'Premiers Secours'), ('Couvertures', 'Couvertures'), ('Articles Scolaires', 'Articles Scolaires'), ('Temps', 'Temps'), ('Livres', 'Livres'), ('Autres', 'Autres')], default='Autres', max_length=100, unique=True),
        ),
    ]
