# Generated by Django 2.0.5 on 2018-07-09 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='updated_at',
        ),
    ]
